### ISSUE TITLE
Error: rsync exited with code 12

### ISSUE THREAD

**Issue by ihor** [FormidableLabs/whackage#12]
Hey guys,

I'm getting the following error:

```
$ whack run packager
error { Error: rsync exited with code 12
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/whackage/node_modules/rsyncwrapper/lib/rsyncwrapper.js:184:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) code: 12 }

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, prune, publish, rb,
    rebuild, repo, restart, root, run, run-script, s, se,
    search, set, shrinkwrap, star, stars, start, stop, t, team,
    test, tst, un, uninstall, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview
```

Any ideas how to resolve it? Thanks!

**Comment by dewwwald** [comment]
Getting the same issue on my end. I am getting this issue on a Machine with SSH access to the host but only when I run the task in jenkins.

**Comment by dewwwald** [comment]
@ihor have you tried using the rsync command line tool directly?

**Comment by ihor** [comment]
Yes, I've tried and it worked well.

**Comment by dewwwald** [comment]
@ihor 

Are you running this tool in any CI environment like jenkins?

**Comment by ihor** [comment]
I had this issue locally on a Mac. Let me know if you need any specific information.

**Comment by jevakallio** [comment]
@ihor @dewwwald we just released a new version 1.2.0 with bunch of bugfixes. The error message you are getting is a little odd, but I think it might be unrelated to rsync.

Any chance you could test if the latest release https://github.com/FormidableLabs/whackage/releases/tag/v1.2.0 fixes this issue?

**Comment by ihor** [comment]
Hey, sorry, I got everything working with [Haul](https://github.com/callstack/haul) and unfortunately, I don't have much time for testing this now.
