### ISSUE TITLE
[whackage] Package my-library is not a registered dependency in my-app

### ISSUE THREAD

**Issue by ghost** [FormidableLabs/whackage#28]
Hello! I'm trying repeat it:
https://formidable.com/blog/2016/12/01/introducing-whackage/

`$ whack link ../../my-library`
here is error:
`[whackage] Package my-library is not a registered dependency in my-app`

After added in dependency I have new error:
```
`events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)`
```

node - v10.7.0
npm - 6.1.0

**Comment by rammoozz** [comment]
I ran into the same issue, ended up manually adding it in ```whackage.json```
```
 "react-native-generic-text": "../react-native-component-boilerplate-master"
```
